add_rules("mode.release")
set_languages("c++20")
target("std")
  set_kind("static")
  add_files("./others/stdmodule/std.mock.cppm", {public = true})
target("work1")
  add_files("work1/1.cpp")
  add_cxxflags("-ftime-trace")
target("work2")
  add_deps("std")
  add_files("work2/2.cpp")
  add_cxxflags("-ftime-trace")
target("work3")
  add_deps("std")
  add_files("work3/main.cpp")
  add_files("work3/animal.cppm")
target("work3_1")
  add_deps("std")
  add_files("work3/main2.cpp")
  add_files("work3/animal.cppm")
target("work4_1")
  add_includedirs("include")
  add_deps("std")
  add_defines("FMT_HEADER_ONLY")
  add_files("work4/main.cpp")
  add_files("work4/export_using_declartion/fmt.cppm", {public = true})
target("work4_2")
  add_includedirs("include")
  add_deps("std")
  add_defines("FMT_HEADER_ONLY")
  add_files("work4/main.cpp")
  add_files("work4/export_extern_cpp/fmt.cppm", {public = true})
target("work5_1")
  add_deps("std")
  add_files("work5/implementation_unit/*.cpp")
  add_files("work5/implementation_unit/my_lib/*.cppm")
  add_files("work5/implementation_unit/my_lib/*.cpp")
target("work5_2")
  add_deps("std")
  add_files("work5/interface_unit/main.cpp")
  add_files("work5/interface_unit/my_lib/impl/*.cppm")
  add_files("work5/interface_unit/my_lib/*.cppm")
target("work5_3")
  add_deps("std")
  add_files("work5/interface_unit/main2.cpp")
  add_files("work5/interface_unit/my_lib/impl/*.cppm")
  add_files("work5/interface_unit/my_lib/*.cppm")
-- target("work5_4")
--   add_deps("std")
--   add_files("work5/partition_unit/main.cpp")
--   add_files("work5/partition_unit/my_lib/*.cppm")